# References:
# https://some-natalie.dev/blog/kaniko-in-arc/
# https://dev.to/ipo/using-kaniko-to-build-and-publish-container-image-with-github-action-on-github-self-hosted-runners-d5m

name: Image Build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 21 1 * *"
  push:
    paths-ignore:
    - .github/**
    - README.md
    branches:
    - master

env:
  COMMIT: master

jobs:
  build:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: ghcr.io/randomcoww/kaniko:debug
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set tag
      run: |
        TAG=$(date -u +'%Y%m%d.%H%M')
        echo TAG=$TAG | tee -a "$GITHUB_ENV"
        echo TAG=$TAG | tee -a "$GITHUB_OUTPUT"

    - name: Build and release container
      run: |
        mkdir -p $DOCKER_CONFIG
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        /kaniko/executor \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository }}:v$TAG" \
          --build-arg COMMIT=$COMMIT \
          --build-arg AWS_ENDPOINT_URL_S3=$AWS_ENDPOINT_URL_S3 \
          --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --skip-unused-stages \
          --target http \
          --cache \
          --push-retry 3
  build-tftp:
    needs:
      - build
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: ghcr.io/randomcoww/kaniko:debug
    permissions:
      contents: read
      packages: write
    env:
      TAG: ${{needs.build.outputs.TAG}}
    steps:
    - name: Build and release container
      run: |
        mkdir -p $DOCKER_CONFIG
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        /kaniko/executor \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository }}:v$TAG-tftp" \
          --build-arg COMMIT=$COMMIT \
          --build-arg AWS_ENDPOINT_URL_S3=$AWS_ENDPOINT_URL_S3 \
          --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --skip-unused-stages \
          --target tftp \
          --cache \
          --push-retry 3
  cleanup:
    needs:
      - build
      - build-tftp
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: docker.io/node:current-alpine
    permissions:
      packages: write
    steps:
      - name: Remove old container images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 6
          token: ${{ secrets.GITHUB_TOKEN }}