# References:
# https://some-natalie.dev/blog/kaniko-in-arc/
# https://dev.to/ipo/using-kaniko-to-build-and-publish-container-image-with-github-action-on-github-self-hosted-runners-d5m

name: Image Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - .github/**
    - README.md
    branches:
    - master

env:
  COMMIT: bd90abf487a6b0500f457193f86ff54fd2be3143

jobs:
  build-tftp:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: gcr.io/kaniko-project/executor:debug
    permissions:
      contents: read
      packages: write
    steps:
    - name: Build and release TFTP container
      run: |
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        /kaniko/executor \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository }}:v$(date -u +'%Y%m%d.%H%M')-tftp" \
          --build-arg COMMIT=$COMMIT \
          --build-arg AWS_ENDPOINT_URL_S3=$AWS_ENDPOINT_URL_S3 \
          --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --target TFTP \
          --push-retry 3

  build-http:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: gcr.io/kaniko-project/executor:debug
    permissions:
      contents: read
      packages: write
    steps:
    - name: Build and release HTTP container
      run: |
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        /kaniko/executor \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository }}:v$(date -u +'%Y%m%d.%H%M')-http" \
          --build-arg COMMIT=$COMMIT \
          --build-arg AWS_ENDPOINT_URL_S3=$AWS_ENDPOINT_URL_S3 \
          --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --target HTTP \
          --push-retry 3