name: iPXE Build
on:
  workflow_dispatch:

env:
  COMMIT: bd90abf487a6b0500f457193f86ff54fd2be3143

jobs:
  build:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: docker.io/alpine:latest
    permissions:
      contents: read
    steps:
    - name: Install dependencies
      run: |
        cd $HOME
        apk add --no-cache \
          g++ \
          xz-dev \
          make \
          perl \
          bash \
          cdrkit \
          git \
          openssl \
          coreutils \
          unzip

        TARGETARCH=$(arch)
        TARGETARCH=${TARGETARCH/x86_64/amd64} && TARGETARCH=${TARGETARCH/aarch64/arm64}

        wget https://dl.min.io/client/mc/release/linux-$TARGETARCH/mc \
          -O mc
        chmod +x mc

        TF_VERSION=$(wget -O - https://api.github.com/repos/hashicorp/terraform/releases/latest |grep tag_name | cut -d '"' -f 4 | tr -d 'v')
        wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_$TARGETARCH.zip \
          -O terraform.zip
        unzip -j terraform.zip terraform
        rm terraform.zip

    - name: Generate CA
      run: |
        cd $HOME
        git clone ${{ github.server_url }}/${{ github.repository }}.git project
        cd project

        $HOME/terraform init
        $HOME/terraform apply -auto-approve

    - name: Get source
      run: |
        cd $HOME
        git clone -b master https://github.com/ipxe/ipxe ipxe
        cd ipxe
        git reset --hard $COMMIT

    - name: Build iPXE
      run: |
        cd $HOME/ipxe/src
        cp $HOME/project/matchbox-ca.pem .
        cp $HOME/project/matchbox-client-cert.pem .
        cp $HOME/project/matchbox-client-key.pem .
        cat matchbox-client-cert.pem matchbox-ca.pem > matchbox-client-full.pem

        cp -r $HOME/project/config/. config/local/
        make \
          bin-$(arch)-efi/ipxe.efi \
          CERT=matchbox-ca.pem \
          TRUST=matchbox-ca.pem \
          DEBUG=tls,x509,certstore,privkey

        mkdir -p $HOME/build
        mv bin-$(arch)-efi/*.efi $HOME/build/

    - name: Push images
      run: |
        cd $HOME
        ./mc cp -q --no-color \
          build/*.efi arc/data-boot/